name: vtudom
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bot_toast: ^4.0.3
  google_nav_bar: ^5.0.6
  flutter_spinkit: ^5.1.0
  google_fonts: ^5.1.0
  url_launcher: ^6.1.12
  line_icons: ^2.0.1
  flutter_riverpod: ^2.3.3
  hive: ^2.2.3
  flutter_svg: ^2.0.4
  video_player: ^2.6.1
  carousel_slider: ^4.2.1
  flutter_launcher_icons: ^0.13.0
  percent_indicator: ^4.2.3
  connectivity_plus: ^4.0.2
  fluttertoast: ^8.2.1
  progress_indicator: ^0.2.2
  circle_progress_bar: ^0.1.2
  flutter_inappwebview: ^5.7.2+3
  permission_handler: ^10.4.3
  google_mobile_ads:
  flutter_downloader: ^1.3.3
  background_downloader: ^7.9.1
  fl_downloader: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
google_fonts: ^4.0.3
google_nav_bar: ^5.0.6
flutter_spinkit: ^5.1.0
bot_toast: ^4.0.3

flutter_launcher_icons: "^0.13.0"
flutter_lints: ^2.0.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  
flutter:

  uses-material-design: true

  assets:
   - assets/images/
